public class GPMSCHSPConstants {
    public static final String SERVICE_TYPE_LEVEL_1 = 'Sector Support and Development';
    public static final String SERVICE_TYPE_LEVEL_2 = 'Goods, Equipment and Assistive Technology';
    public static final String SERVICE_SUB_CARE_TYPE_1 = 'Service System Development';
    public static final String SERVICE_SUB_CARE_TYPE_2 = 'Community and Home Support';
    public static final String ACPR_REGION_1 = 'Eastern Metro';
    public static final String ACPR_REGION_2 = 'Central West';
    public static final String ACPR_REGION_3 = 'Loddon-Mallee';
    public static final String ACPR_REGION_4 = 'Metropolitan South';
    public static final String TEST_PARTYID_1 = '3-V547UZ';
    public static final String TEST_PARTYID_2 = '4-CJIMO97';
}